### ISSUE TITLE
no restart after firmware download

### ISSUE THREAD

**Issue by therwastl07** [martin-ger/esp_wifi_repeater#410] opened 2020-08-13 19:32 UTC
Hello!

I appreciate your effort and tried to use your system because the auto-mesh is rather unique.
I tried to download the latest onto a 12-E and a 12-F NodeMCU and in both cases they did not start to show the AP.
With the 12-E (for example), I was able to dowload the firmware with the "download tool", after restart and with putty and 74880 baud (only speed without garbage) I read after the reboot a line like:

ets Jan 8 2013,rst  cause:2 , boot mode:(3,6)
ets_main.c

Does anyone has an idea - would be jolly good!!
Thanks - TW7

**Comment by imayoda** [comment] 2020-09-28 14:18
some good hints that saved me a lot of times with 8266:
- ensure good power supply (some boards have flaky regulators or usb connectors)
- erasing all flash contents can bring a solution sometimes
- ensure the right flash reading mode (DIO is usually accepted, but slower solutions like DOUT are present on some manufacturer boards like sonoff basic etc.).

btw if program succesfully starts, it changes baud to 115200. :)

**Comment by mikedarzen** [comment] 2020-11-02 02:57
I saw the same error message.  It seems the problem is in how you download the firmware.   Just right clicking the file (in Windows) didn't work for me.  I suspect it was transferred in a non binary format.   I downloaded the zip file of the repo and flashed from those files and it the error message went away and it booted as expected.

**Comment by imayoda** [comment] 2020-11-19 01:49
@mikedarzen you pointed it right, downloading .zip is always the good thing to do, at least when you are browsing the web github.. :)

**Comment by imayoda** [comment] 2020-11-19 01:49
would be nice to hear news from OP so we can close this issue somehow :)

**Comment by BoffinTecs** [comment] 2020-11-21 16:15
Me I have the esp-01s. I managed to flash the firmware successful but when I restart it in non-programming mode, nothing seems to be happening, I can't see the default AP and when I send commands I don't receive any response.
Thanks in advance.

**Comment by therwastl07** [comment] 2020-12-13 09:25
Sorry for the delay.
I got it running with a capacitor on the power pin.
Grrrr…



Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: imayoda<mailto:notifications@github.com>
Gesendet: Donnerstag, 19. November 2020 02:50
An: martin-ger/esp_wifi_repeater<mailto:esp_wifi_repeater@noreply.github.com>
Cc: therwastl07<mailto:torper7@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [martin-ger/esp_wifi_repeater] no restart after firmware download (#410)


would be nice to hear news from OP so we can close this issue somehow :)

**Closed** 2020-12-13 10:17 UTC
